spring:
  application:
    name: nba-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import: nacos:nba-server.yml

nba:
  key: 6d15dd51c1fb44f09453833949930ba9
  url: https://api.sportsdata.io/v3/nba/scores/json/
