// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nbaservice_protos.proto
// Protobuf Java Version: 4.29.3

package com.diy.vcp.grpc.core;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .grpc.HelloRequest requests = 2;</code>
   */
  java.util.List<com.diy.vcp.grpc.core.HelloRequest> 
      getRequestsList();
  /**
   * <code>repeated .grpc.HelloRequest requests = 2;</code>
   */
  com.diy.vcp.grpc.core.HelloRequest getRequests(int index);
  /**
   * <code>repeated .grpc.HelloRequest requests = 2;</code>
   */
  int getRequestsCount();
  /**
   * <code>repeated .grpc.HelloRequest requests = 2;</code>
   */
  java.util.List<? extends com.diy.vcp.grpc.core.HelloRequestOrBuilder> 
      getRequestsOrBuilderList();
  /**
   * <code>repeated .grpc.HelloRequest requests = 2;</code>
   */
  com.diy.vcp.grpc.core.HelloRequestOrBuilder getRequestsOrBuilder(
      int index);
}
