spring:
  application:
    name: batch-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  quartz:
    jdbc:
      initialize-schema: never
    quartz:
      job-store-type: jdbc
      properties:
        org:
          quartz:
            scheduler:
              instanceId: AUTO
            jobStore:
              class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
              isClustered: true
              clusterCheckinInterval: 20000
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
  config:
    import: nacos:batch-server.yml