spring:
  netty:
    leak-detection: advanced
  application:
    name: time-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        enabled: true
  config:
    import: optional:nacos:config.yml
server:
  port: 10008
