CREATE TABLE `team` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `team_id` int NOT NULL DEFAULT '0' COMMENT '球队id',
  `key` varchar(10) NOT NULL DEFAULT '' COMMENT '球队缩写',
  `active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否现役',
  `city` varchar(50) NOT NULL DEFAULT '' COMMENT '城市',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '球队名',
  `league_id` int NOT NULL DEFAULT '0' COMMENT '联盟id',
  `stadium_id` int NOT NULL DEFAULT '0' COMMENT '球馆id',
  `conference` varchar(20) NOT NULL DEFAULT '' COMMENT '分区',
  `division` varchar(20) NOT NULL DEFAULT '' COMMENT '赛区',
  `primary_color` varchar(10) NOT NULL DEFAULT '' COMMENT '主色',
  `secondary_color` varchar(10) NOT NULL DEFAULT '' COMMENT '次色',
  `tertiary_color` varchar(10) NOT NULL DEFAULT '' COMMENT '第三色',
  `quaternary_color` varchar(10) NOT NULL DEFAULT '' COMMENT '第四色',
  `wikipedia_logo_url` varchar(300) NOT NULL DEFAULT '' COMMENT 'logo地址',
  `global_team_id` int NOT NULL DEFAULT '0' COMMENT '全局球队id',
  `nba_dot_com_team_id` int NOT NULL DEFAULT '0' COMMENT 'nba.com球队id',
  `head_coach` varchar(100) NOT NULL DEFAULT '' COMMENT '主教练',
  `create_user` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` int NOT NULL DEFAULT '0' COMMENT '是否删除0.否1.是',
  PRIMARY KEY (`id`),
  KEY `idx_team_id` (`team_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='球队信息表';

CREATE TABLE `current_season` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `season` int NOT NULL DEFAULT '0' COMMENT '赛季',
  `start_year` int NOT NULL DEFAULT '0' COMMENT '开始年份',
  `end_year` int NOT NULL DEFAULT '0' COMMENT '结束年份',
  `description` varchar(50) NOT NULL DEFAULT '' COMMENT '描述',
  `regular_season_start_date` datetime DEFAULT NULL COMMENT '常规赛开始时间',
  `post_season_start_date` datetime DEFAULT NULL COMMENT '季后赛开始时间',
  `season_type` varchar(10) NOT NULL DEFAULT '' COMMENT '赛季类型',
  `api_season` varchar(20) NOT NULL DEFAULT '' COMMENT 'api赛季',
  `create_user` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` int NOT NULL DEFAULT '0' COMMENT '是否删除0.否1.是',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='当前赛季信息表';
